--- # Create a deployment and service for tomcat web server
- hosts: Kube
  gather_facts: true
  tasks:
    - name: Create deployment
      command: kubectl apply -f tomcat_deploy.yaml
    - name: Create service
      command: kubectl apply -f tomcat_service.yaml
