apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deploy
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: tomcat-pod
      labels:
        tier: frontend
    spec:
      containers:
        - name: tomcat-container
          image: basavarjteli/my_tomcat:v1
          ports:
            - containerPort: 8080
