apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat_deploy
  labels:
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      name: tomcat_pod
      labels:
        tier: frontend
    spec:
      containers:
        name: tomcat_container
        image: basavarjteli/my_tomcat:v1
