apiVersion: v1
kind: Service
metadata:
  name: tomcat_service
  labels:
    tier: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30008
  selector:
    tier: frontend
